In [4]:
a = [10,16,985,25,6,25,]
a

[10, 16, 985, 25, 6, 25]

In [5]:
a.append(5)
a

[10, 16, 985, 25, 6, 25, 5]

In [6]:
a[2]

985

In [7]:
a[2:]

[985, 25, 6, 25, 5]

In [8]:
a[-1]

5

In [9]:
a[-5]

985

In [10]:
a

[10, 16, 985, 25, 6, 25, 5]

In [11]:
a = a[-1::]
a

[5]

In [12]:
a

[5]

In [2]:
a = [10, 16, 985, 25, 6, 25, 5]
a[::-1]
a.reverse()

In [14]:
a

[10, 16, 985, 25, 6, 25, 5]

In [15]:
a.insert(2, 36)

In [16]:
a

[10, 16, 36, 985, 25, 6, 25, 5]

In [17]:
a.index(36)


2

In [18]:
a.pop(2)


36

In [19]:
a

[10, 16, 985, 25, 6, 25, 5]

In [20]:
a.pop()

5

In [21]:
a

[10, 16, 985, 25, 6, 25]

In [22]:
a.remove(985)
a

[10, 16, 25, 6, 25]

In [23]:
del a[2:]
a

[10, 16]

In [24]:
a = [10, 16, 985, 25, 6, 25, 5]
a


[10, 16, 985, 25, 6, 25, 5]

In [25]:
min(a)

5

In [26]:
max(a)

985

In [27]:
sum(a)

1072

In [28]:
a.sort()

In [29]:
a

[5, 6, 10, 16, 25, 25, 985]

In [36]:
c = ['name', [3,6,9,8,5,2]]
c[1]
c[1][2]

9

In [33]:
b = ['name', 3.26, True, 6 ]
b.

['name', 3.26, True, 6]

In [37]:
#dealing with tuples 
tup = (2,4,6,8,10)
tup
#tuple is a non mutable datatye with limited operations

(2, 4, 6, 8, 10)

In [39]:
tup[1]

4

In [41]:
tup.index(4)

1

In [43]:
#dealing with set
s = {1,6,8,9,5,6,3}
s

{1, 3, 5, 6, 8, 9}

In [44]:
s

{1, 3, 5, 6, 8, 9}

In [46]:
max(s)


9

In [47]:
s.add(7)
s

{1, 3, 5, 6, 7, 8, 9}

In [49]:
s.pop()

1

In [50]:
s.remove(3)

In [51]:
s

{5, 6, 7, 8, 9}

In [11]:
s = {0,1,2,3,4,5,6,7,8,9}
s1 = {2,4,6,8}

In [12]:
s.union(s1)
s.intersection(s1)
s.difference(s1)
s1.issubset(s)

True

In [53]:
a = range(0,10,1)

In [54]:
type(a)

range

In [58]:
a = list( range(1,10))

In [59]:
type(a)

list

In [60]:
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [61]:
b = list(range(1,11,2))

In [62]:
b

[1, 3, 5, 7, 9]

In [3]:
#all about dictionaries 
dic = {1:"misba", 2:"boomi",3:'tony', 4:"sharanraj"}
dic[1]

'misba'

In [4]:
dic[3]

'tony'

In [5]:
dic[1] = 'mis'

In [6]:
dic[1]

'mis'

In [7]:
dic.get(3,"student not found")

'tony'

In [8]:
dic.pop(3)
dic

{1: 'mis', 2: 'boomi', 4: 'sharanraj'}

In [9]:
dic.keys()


dict_keys([1, 2, 4])

In [10]:
dic.items()

{1: 'mis', 2: 'boomi', 4: 'sharanraj'}

In [28]:
keys = [1,2,3,4,5]
values = ['a','b','c','d','e']
zip(keys, values)

In [29]:
data = dict(zip(keys, values))
data

{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e'}

In [30]:
i = 7
j = float(i)
j#7.0

7.0

In [31]:
#comparision operators
a, b = 5, 4 
a

5

In [32]:
a == b

False

In [33]:
a < b

True

In [34]:
a > b

False

In [35]:
a != b

True

In [36]:
a <= b

True

In [37]:
a >= b

False

In [43]:
#logical operators
a = 5 
b = 6 
# P   and   q     
a < b and a < 5
#  T  and   F
# P   and   q     
a < 5 or a < 5
#  F  or   F
not a > b

True

In [44]:
#0 1 2 .... 9 dec 
#bin 0 1
# octal 0 8
# hexa dec 0 1 2....9 a b ....
bin(9)

'0b1001'

In [45]:
0b1001

9

In [46]:
oct(9)

'0o11'

In [47]:
0o11


9

In [48]:
hex(9)

'0x9'

In [49]:
0x9

9

## arrays 

In [11]:
from array import *

arr = array('i', [3,6,9,8,5,2])
arr


array('i', [3, 6, 9, 8, 5, 2])

In [9]:
arr.typecode

'f'

In [2]:
from numpy import *
arr = array([3,6,9,8,5,2])
arr

array([3, 6, 9, 8, 5, 2])

In [3]:
arr += 5
arr

array([ 8, 11, 14, 13, 10,  7])

In [4]:
arr1 = array([36,9,8,5,41,5])
arr2 = arr + arr1
arr2

array([44, 20, 22, 18, 51, 12])

In [5]:
arr3 = concatenate((arr ,arr1))
arr3

array([ 8, 11, 14, 13, 10,  7, 36,  9,  8,  5, 41,  5])

In [6]:
a = 10 
b = 10 
id(a)
#


140711405016136

In [7]:
id(b)

140711405016136

In [8]:
arr3 = arr 
id(arr)

2132730094736

In [9]:
id(arr3)

2132730094736

In [10]:
arr3 = arr.view()
id(arr3)

2132730087152

In [11]:
arr3 = arr.copy()
id(arr3)

2132833910576

In [16]:
arr1 = array([[3,6],
        [5,8]])
arr1.ndim

2

In [17]:
arr2 = array([
    [6,6],
    [7,1]])
arr2.ndim

2

In [18]:
m1 = matrix(arr1)
m2 = matrix(arr2)
m1
m2
m3 = m1*m2
m3

matrix([[60, 24],
        [86, 38]])

In [19]:
arr1.flatten()

array([3, 6, 5, 8])

In [21]:
arr1.reshape(2,2)


array([[3, 6],
       [5, 8]])